### ISSUE TITLE
Pangadamus says Bitcoin won't EVER go below 10k again.

### ISSUE THREAD

**Issue by andrecarlucci** [andrecarlucci/midnight-bets#4]
## Apostadores
- Petrucio
- Carlucci

## Aposta
Petrucio diz que Bitcoin price won't go below 10k. 
Price will be tracked by https://www.coinmarketcap.com/

## Deadline
27-Jul-2021

## Prêmio da Aposta
1 cerveja boa

## Validação
Lembre-se: esta aposta só é valida se todos os apostadores comentarem este post com um :thumbsup:

**Comment by gbmachado** [comment]
10k reais?

**Comment by andrecarlucci** [comment]
10K Dólares, o https://www.coinmarketcap.com/ só trackeia em dolar.
@petrucio-br, dá um OK aqui pra confirmar.

**Comment by petrucio-br** [comment]
👍

**Comment by andrecarlucci** [comment]
Como podemos verificar em  https://www.coinmarketcap.com/, Bitcoin caiu para menos de 10K dólares me fazendo assim o vencedor desta aposta.
@petrucio-br , me deves uma cerveja :)

![image](https://user-images.githubusercontent.com/66689/95302055-b5de9a00-0881-11eb-8605-61bbce3a88af.png)
